apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-secrets
  namespace: default
data:
  url: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOmFkbWluQGhvc3QuZG9ja2VyLmludGVybmFsOjU0MzIvbXlkYj9zY2hlbWE9cHVibGljCg=="
